#!/bin/bash
#
#By: Ivan Davydenko
#
#Date 2025 Oct 05
#
#Porpuse:Show system information


hostName=$(hostname)
date=$(date)
userName=$(whoami)
source /etc/os-release
osName=$PRETTY_NAME
runTime=$(uptime)
cpuInfo=$(lscpu | grep "Model name" | cut -d: -f2 | xargs)
ramInfo=$(free -h | awk '/Mem:/ {print $2}')
diskNames=$(sudo lshw -class disk | grep "product:" | cut -d: -f2 | xargs)
diskSizes=$(df -h | grep "^/dev/" | awk '{print $2}')
gpuInfo=$(sudo lshw -class display| grep -E "product|vendor" | cut -d: -f2 | xargs)
ipInfo=$(ip a | grep "inet " | grep -v "127.0.0.1" | awk '{print $2}')
defaultGateWay=$(ip r | grep default | awk '{print $3}')
dnsInfo=$(resolvectl status | grep "Current DNS Server" | cut -d: -f2 | xargs)

logedInUsers=$(users)
freeDiskSpace=$( df -h | grep "^/dev/" | awk '{print $1, $4}')
numberOfProses=$(ps | wc -l)
loadAvarageInfo=$(uptime | cut -d: -f5 | xargs)
activePorts=$(ss -tulpn | tail -n +2 | cut -d':' -f2 | cut -d' ' -f1 | xargs)
ufwStatus=$(sudo ufw status | cut -d: -f2| xargs)



echo
echo "System Report for $hostName generated by $userName, on $date"
echo
echo "System information"
echo "--------------------"
echo "Operating System: $osName"
echo "Uptime: $runTime"
echo "CPU information: $cpuInfo"
echo "Ram information: $ramInfo"
echo "Disk(s) information fore each respectevly: $diskNames $diskSizes"
echo "GPU information: $gpuInfo"
echo "IP addres of the host: $ipInfo"
echo "Default gateway: $defaultGateWay"
echo "DNS server: $dnsInfo"
echo
echo "System Status"
echo "----------------------"
echo "Users loged in: $logedInUsers"
echo "Disk space: $freeDiskSpace"
echo "Procses count: $numberOfProses"
echo "Load avreages: $loadAvarageInfo"
echo "Listening network ports: $activePorts"
echo "UFW status: $ufwStatus"

